// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: v2ray.com/core/common/net/address.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace V2Ray.Core.Common.Net {

  /// <summary>Holder for reflection information generated from v2ray.com/core/common/net/address.proto</summary>
  public static partial class AddressReflection {

    #region Descriptor
    /// <summary>File descriptor for v2ray.com/core/common/net/address.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AddressReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cid2MnJheS5jb20vY29yZS9jb21tb24vbmV0L2FkZHJlc3MucHJvdG8SFXYy",
            "cmF5LmNvcmUuY29tbW9uLm5ldCI3CgpJUE9yRG9tYWluEgwKAmlwGAEgASgM",
            "SAASEAoGZG9tYWluGAIgASgJSABCCQoHYWRkcmVzc0I6Chljb20udjJyYXku",
            "Y29yZS5jb21tb24ubmV0UAFaA25ldKoCFVYyUmF5LkNvcmUuQ29tbW9uLk5l",
            "dGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::V2Ray.Core.Common.Net.IPOrDomain), global::V2Ray.Core.Common.Net.IPOrDomain.Parser, new[]{ "Ip", "Domain" }, new[]{ "Address" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Address of a network host. It may be either an IP address or a domain address.
  /// </summary>
  public sealed partial class IPOrDomain : pb::IMessage<IPOrDomain> {
    private static readonly pb::MessageParser<IPOrDomain> _parser = new pb::MessageParser<IPOrDomain>(() => new IPOrDomain());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IPOrDomain> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::V2Ray.Core.Common.Net.AddressReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IPOrDomain() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IPOrDomain(IPOrDomain other) : this() {
      switch (other.AddressCase) {
        case AddressOneofCase.Ip:
          Ip = other.Ip;
          break;
        case AddressOneofCase.Domain:
          Domain = other.Domain;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IPOrDomain Clone() {
      return new IPOrDomain(this);
    }

    /// <summary>Field number for the "ip" field.</summary>
    public const int IpFieldNumber = 1;
    /// <summary>
    /// IP address. Must by either 4 or 16 bytes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Ip {
      get { return addressCase_ == AddressOneofCase.Ip ? (pb::ByteString) address_ : pb::ByteString.Empty; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        addressCase_ = AddressOneofCase.Ip;
      }
    }

    /// <summary>Field number for the "domain" field.</summary>
    public const int DomainFieldNumber = 2;
    /// <summary>
    /// Domain address.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Domain {
      get { return addressCase_ == AddressOneofCase.Domain ? (string) address_ : ""; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        addressCase_ = AddressOneofCase.Domain;
      }
    }

    private object address_;
    /// <summary>Enum of possible cases for the "address" oneof.</summary>
    public enum AddressOneofCase {
      None = 0,
      Ip = 1,
      Domain = 2,
    }
    private AddressOneofCase addressCase_ = AddressOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddressOneofCase AddressCase {
      get { return addressCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearAddress() {
      addressCase_ = AddressOneofCase.None;
      address_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IPOrDomain);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IPOrDomain other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ip != other.Ip) return false;
      if (Domain != other.Domain) return false;
      if (AddressCase != other.AddressCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (addressCase_ == AddressOneofCase.Ip) hash ^= Ip.GetHashCode();
      if (addressCase_ == AddressOneofCase.Domain) hash ^= Domain.GetHashCode();
      hash ^= (int) addressCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (addressCase_ == AddressOneofCase.Ip) {
        output.WriteRawTag(10);
        output.WriteBytes(Ip);
      }
      if (addressCase_ == AddressOneofCase.Domain) {
        output.WriteRawTag(18);
        output.WriteString(Domain);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (addressCase_ == AddressOneofCase.Ip) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Ip);
      }
      if (addressCase_ == AddressOneofCase.Domain) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Domain);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IPOrDomain other) {
      if (other == null) {
        return;
      }
      switch (other.AddressCase) {
        case AddressOneofCase.Ip:
          Ip = other.Ip;
          break;
        case AddressOneofCase.Domain:
          Domain = other.Domain;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ip = input.ReadBytes();
            break;
          }
          case 18: {
            Domain = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
