// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: v2ray.com/core/transport/internet/tcp/config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace V2Ray.Core.Transport.Internet.Tcp {

  /// <summary>Holder for reflection information generated from v2ray.com/core/transport/internet/tcp/config.proto</summary>
  public static partial class ConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for v2ray.com/core/transport/internet/tcp/config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJ2MnJheS5jb20vY29yZS90cmFuc3BvcnQvaW50ZXJuZXQvdGNwL2NvbmZp",
            "Zy5wcm90bxIhdjJyYXkuY29yZS50cmFuc3BvcnQuaW50ZXJuZXQudGNwGjB2",
            "MnJheS5jb20vY29yZS9jb21tb24vc2VyaWFsL3R5cGVkX21lc3NhZ2UucHJv",
            "dG8iTwoGQ29uZmlnEj8KD2hlYWRlcl9zZXR0aW5ncxgCIAEoCzImLnYycmF5",
            "LmNvcmUuY29tbW9uLnNlcmlhbC5UeXBlZE1lc3NhZ2VKBAgBEAJCUgolY29t",
            "LnYycmF5LmNvcmUudHJhbnNwb3J0LmludGVybmV0LnRjcFABWgN0Y3CqAiFW",
            "MlJheS5Db3JlLlRyYW5zcG9ydC5JbnRlcm5ldC5UY3BiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::V2Ray.Core.Common.Serial.TypedMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::V2Ray.Core.Transport.Internet.Tcp.Config), global::V2Ray.Core.Transport.Internet.Tcp.Config.Parser, new[]{ "HeaderSettings" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Config : pb::IMessage<Config> {
    private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::V2Ray.Core.Transport.Internet.Tcp.ConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config(Config other) : this() {
      headerSettings_ = other.headerSettings_ != null ? other.headerSettings_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config Clone() {
      return new Config(this);
    }

    /// <summary>Field number for the "header_settings" field.</summary>
    public const int HeaderSettingsFieldNumber = 2;
    private global::V2Ray.Core.Common.Serial.TypedMessage headerSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::V2Ray.Core.Common.Serial.TypedMessage HeaderSettings {
      get { return headerSettings_; }
      set {
        headerSettings_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(HeaderSettings, other.HeaderSettings)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (headerSettings_ != null) hash ^= HeaderSettings.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (headerSettings_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(HeaderSettings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (headerSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HeaderSettings);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Config other) {
      if (other == null) {
        return;
      }
      if (other.headerSettings_ != null) {
        if (headerSettings_ == null) {
          headerSettings_ = new global::V2Ray.Core.Common.Serial.TypedMessage();
        }
        HeaderSettings.MergeFrom(other.HeaderSettings);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (headerSettings_ == null) {
              headerSettings_ = new global::V2Ray.Core.Common.Serial.TypedMessage();
            }
            input.ReadMessage(headerSettings_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
